### ISSUE TITLE
Is dehazing.py a training program or a verification program?

### ISSUE THREAD

**Issue by Kayla2714** [XLearning-SCU/2021-IJCV-YOLY#3]

**Comment by XLearning-SCU** [comment]
I am sorry to reply so late. YOLY is an "untrained" method, which means that YOLY bypasses the conventional training paradigm of deep models on hazy-clean pairs and only need to optimize its parameters on observed ones. Thus, dehazing.py is both training program and verification program, because it optimizes parameters in this file and test the performance as well.
