### ISSUE TITLE
code

### ISSUE THREAD

**Issue by chenhuiphd** [XLearning-SCU/2021-IJCV-YOLY#8]
hi， The following error occurs in the  means = self.fc1(data)， RuntimeError: size mismatch, m1: [1 x 25088], m2: [18432 x 100] at c:\a\w\1\s\tmp_conda_3.7_110206\conda\conda-bld\pytorch_1550401474361\work\aten\src\thc\generic/THCTensorMathBlas.cu:266
How to correct it？thanks

**Comment by GitHuber-ops** [comment]
hi, chenhuiphd! 
Have you solved this problem and can you provide some help？Thx

**Comment by yousaLING** [comment]
> hi, chenhuiphd! Have you solved this problem and can you provide some help？Thx

Hi, GitHuber-ops! I have found the reason. The error occurred because the code automatically crops the images in the RESIDE dataset, leading to inconsistent sizes among the processed images. As a result, the subsequent operations encountered issues due to the mismatch in image dimensions. You don't need to perform any preprocessing on the RESIDE dataset as the code is designed to handle the necessary cropping and resizing internally.
The relevant code is here:
https://github.com/XLearning-SCU/2021-IJCV-YOLY/blob/master/utils/image_io.py#L280
Caused by the operation of crop_white_side
>
